package com.jeong.runninggoaltracker.feature.ai_coach.contract

object SmartWorkoutLogContract {
    const val LOG_TAG = "SmartWorkoutPose"
    const val EVENT_REP_COUNT = "repCount"
    const val EVENT_FRAME_SKIP = "frameSkip"
    const val EVENT_WARNING = "warning"
    const val EVENT_ATTEMPT_START = "attemptStart"
    const val EVENT_ATTEMPT_END = "attemptEnd"
    const val EVENT_DEPTH_REACHED = "depthReached"
    const val EVENT_FULL_BODY_VISIBILITY = "fullBodyVisible"
    const val EVENT_FEEDBACK_EMIT = "feedbackEmit"
    const val TRANSITION_PREFIX = "transition"
    const val SOURCE_ANALYZER = "analyzer"
    const val SOURCE_UI = "ui"
    const val KEY_FROM = "from"
    const val KEY_TO = "to"
    const val KEY_TIMESTAMP = "ts"
    const val KEY_SIDE = "side"
    const val KEY_PHASE = "phase"
    const val KEY_KNEE = "knee"
    const val KEY_TRUNK_TILT = "trunkTilt"
    const val KEY_TRUNK_TO_THIGH = "trunkToThigh"
    const val KEY_REASON = "reason"
    const val KEY_REP_COUNT = "repCount"
    const val KEY_SOURCE = "source"
    const val KEY_FEEDBACK = "feedback"
    const val KEY_METRIC = "metric"
    const val KEY_VALUE = "value"
    const val KEY_THRESHOLD = "threshold"
    const val KEY_OPERATOR = "operator"
    const val KEY_STATE = "state"
    const val KEY_ATTEMPT_ACTIVE = "attemptActive"
    const val KEY_DEPTH_REACHED = "depthReached"
    const val KEY_KNEE_MIN = "kneeMin"
    const val KEY_FULL_BODY_VISIBLE = "fullBodyVisible"
    const val KEY_INVISIBLE_DURATION = "invisibleDurationMs"
    const val LOG_SEPARATOR = " "
    const val LOG_ASSIGN = "="
}
