package com.jeong.runninggoaltracker.feature.home.contract

const val HOME_ZERO_DOUBLE = 0.0
const val HOME_ZERO_FLOAT = 0f
const val HOME_ZERO_INT = 0
const val HOME_WEIGHT_ONE = 1f
const val HOME_CALENDAR_COLUMN_COUNT = 7
const val HOME_PREVIEW_DISTANCE_SCALE_TENTHS = 10.0
const val HOME_PREVIEW_TOTAL_DISTANCE_TENTHS = 125
const val HOME_PREVIEW_ACTIVITY_FIRST_DISTANCE_TENTHS = 52
const val HOME_PREVIEW_ACTIVITY_SECOND_COUNT = 18
const val HOME_PREVIEW_DAY_MILLIS = 86_400_000L
const val HOME_PREVIEW_EPOCH_DAYS = 20_000L
const val HOME_PREVIEW_TOTAL_CALORIES = 740
const val HOME_PREVIEW_TOTAL_DURATION_MINUTES = 85
const val HOME_PREVIEW_AVERAGE_PACE_MINUTES = 6
const val HOME_PREVIEW_AVERAGE_PACE_SECONDS = 48
const val HOME_PREVIEW_ACTIVITY_FIRST_ID = 1L
const val HOME_PREVIEW_ACTIVITY_FIRST_DURATION_MINUTES = 32
const val HOME_PREVIEW_ACTIVITY_SECOND_ID = 2L
const val HOME_PREVIEW_ACTIVITY_SECOND_DURATION_MINUTES = 20
